version: '3'
services:
  # db:
  #   image: mysql:5.7
  #   container_name: mysql
  #   volumes: # host/docker間で共有するデータを指定
  #     - "${HOME}/nextjs_test:/var/lib/mysql"
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #     TZ: "Asia/Tokyo"
  #   ports:
  #     - "3306:3306"
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - nextjs
    # restart: always
  nextjs:
    build: ./
    container_name: nextjs-ts
    volumes:
      - ./app:/usr/src/app
    command: "yarn dev"
    ports:
      - "4001:3000"
    environment:
      - "CHOKIDAR_USEPOLLING=true" #for hot-reload
    # links:
    #   - db
    # restart: always